"""Embed the pictures the result card needs (win / lose / idle poses + arena backgrounds) as data: URIs,
so 'СОХРАНИТЬ' also works when the game is opened as a local file (file:// images taint the canvas)."""
import base64, io, json, os
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, 'sprites.js')).read()
meta = json.loads(src[src.index('{'):src.rindex('}') + 1])
out = {'spr': {}, 'bg': {}}
def uri(im, fmt, **kw):
    b = io.BytesIO(); im.save(b, fmt, **kw)
    return f'data:image/{fmt.lower()};base64,' + base64.b64encode(b.getvalue()).decode()
for cid, poses in meta.items():
    out['spr'][cid] = {}
    for p in ('win', 'lose', 'idle'):
        if p in poses:
            out['spr'][cid][p] = uri(Image.open(os.path.join(ROOT, poses[p]['src'])), 'PNG', optimize=True)
for f in sorted(x for x in os.listdir(os.path.join(ROOT, 'assets/backgrounds')) if os.path.isfile(os.path.join(ROOT, 'assets/backgrounds', x))):
    im = Image.open(os.path.join(ROOT, 'assets/backgrounds', f)).convert('RGB')
    im.thumbnail((1200, 630))
    out['bg'][f.split('.')[0]] = uri(im, 'JPEG', quality=72)
open(os.path.join(ROOT, 'share_assets.js'), 'w').write('// Generated by tools/build_share_assets.py\nwindow.SHARE_ASSETS = ' + json.dumps(out) + ';\n')
print(os.path.getsize(os.path.join(ROOT, 'share_assets.js')) // 1024, 'KB')
