"""Split ChatGPT two-pose sheets into wind-up frames (light_0 / heavy_0) per fighter."""
import json, types, sys
import numpy as np
from PIL import Image
src = open('build_gen.py').read().split("cleaned = {k:")[0].replace("CID = sys.argv[1] if len(sys.argv) > 1 else 'maybe'", "CID = 'maybe'")
mod = types.ModuleType('bg'); exec(src, mod.__dict__)
clean, scale, anchor = mod.clean, mod.scale, mod.anchor
U = '/root/.claude/uploads/0304dbb7-6743-5d1e-8047-f08d9f58bf9d/'
# file, which figure indexes are (light, heavy), index of the figure whose top is the head (for scale)
SRC = {
 'face':  ('9bf41663', (0, 1), 1), 'korzh': ('18b1e73b', (0, 1), 1), 'slava': ('e9bba9d1', (0, 1), 1),
 'kreed': ('f0309c63', (0, 1), 1), 'atl':   ('e31773e8', (0, 1), 1), 'maybe': ('f2d8d57e', (0, 1), 1),
 'morgen':('f428690b', (0, 1), 1), 'noize': ('76f01836', (0, 1), 0), 'oxxxy': ('5caeb837', (0, 1), 0),
 'guf':   ('d0759027', (0, 1), 1),
}
meta = json.load(open('sprite_meta.json'))
newmeta = {}
def figures(path):
    im = Image.open(path).convert('RGBA'); a = np.array(im).astype(int)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    fg = ~((g > 150) & (g > r + 60) & (g > b + 60)) & (a[..., 0] + a[..., 1] + a[..., 2] > 40)  # not green, not black bar
    cols = fg.sum(0) > 2
    runs, start = [], None
    for x, c in enumerate(list(cols) + [False]):
        if c and start is None: start = x
        if not c and start is not None:
            if x - start > 40: runs.append([start, x])
            start = None
    # merge runs separated by tiny gaps
    merged = []
    for rr in runs:
        if merged and rr[0] - merged[-1][1] < 25: merged[-1][1] = rr[1]
        else: merged.append(rr)
    return im, merged
for cid, (fid, (li, hi), refi) in SRC.items():
    im, figs = figures(U + fid + '-image.png')
    assert len(figs) >= 2, (cid, figs)
    crops = []
    for x0, x1 in figs:
        c = im.crop((max(0, x0 - 6), 0, min(im.width, x1 + 6), im.height))
        c.save('wind_gen/tmp.png'); crops.append(clean('wind_gen/tmp.png'))
    idle = Image.open(f'game/assets/sprites/{cid}_idle.png'); bb = idle.getbbox(); IH = bb[3] - bb[1] - 2
    k = IH * 0.98 / crops[refi].height * {'atl': 0.86, 'face': 1.04}.get(cid, 1.0)
    for pose, idx in (('light_0', li), ('heavy_0', hi)):
        sm = scale(crops[idx], k)
        ax, ay = anchor(sm)
        sm.save(f'game/assets/sprites/{cid}_{pose}.png', optimize=True)
        meta.setdefault(cid, {})[pose] = {'src': f'assets/sprites/{cid}_{pose}.png', 'ax': round(ax), 'ay': round(ay)}
        newmeta.setdefault(cid, {})[pose] = meta[cid][pose]
    print(cid, len(figs), [c.size for c in crops], round(k, 3))
# guf/noize/oxxxy/morgen live in sprite_meta.json; the rest in <cid>_meta.json
for cid, m in newmeta.items():
    if cid in ('guf', 'noize', 'oxxxy', 'morgen'): continue
    mm = json.load(open(f'{cid}_meta.json')); mm.update(m); json.dump(mm, open(f'{cid}_meta.json', 'w'), indent=1)
for c in ['maybe', 'kreed', 'slava', 'atl', 'korzh', 'face']: meta.pop(c, None)
json.dump(meta, open('sprite_meta.json', 'w'), indent=1)
m = json.load(open('sprite_meta.json'))
for c in ['maybe', 'kreed', 'slava', 'atl', 'korzh', 'face']:
    mm = json.load(open(f'{c}_meta.json')); mm.pop('_whip_root', None); m[c] = mm
open('game/sprites.js', 'w').write('// Generated by tools/build_sprites.py, build_gen.py, build_windup.py: frame image + anchor (feet centre) per pose.\nconst SPRITE_META = ' + json.dumps(m, separators=(',', ':')) + ';\n')
