"""Split ChatGPT 3-pose sheets into crouch_light / overhead / air_kick per fighter."""
import json, types, sys
import numpy as np
from PIL import Image
src = open('build_gen.py').read().split("cleaned = {k:")[0].replace("CID = sys.argv[1] if len(sys.argv) > 1 else 'maybe'", "CID = 'maybe'")
mod = types.ModuleType('bg'); exec(src, mod.__dict__)
clean, scale, anchor = mod.clean, mod.scale, mod.anchor
U = '/root/.claude/uploads/0304dbb7-6743-5d1e-8047-f08d9f58bf9d/'
SRC = {'korzh':'c597d902','atl':'37b4a88f','chip':'867d7473','face':'18d61b09','slava':'9dc28c0b',
       'kreed':'c7d8d7d9','maybe':'d80419e2','morgen':'6c471847','oxxxy':'5d372d1c','noize':'75922362','guf':'06fd1d76'}
FIX = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
POSES = ('crouch_light', 'overhead', 'air_kick')
def figures(path):
    im = Image.open(path).convert('RGBA'); a = np.array(im).astype(int)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    fg = ~((g > 150) & (g > r + 60) & (g > b + 60)) & (r + g + b > 40)
    cols = fg.sum(0) > 2
    runs, start = [], None
    for x, c in enumerate(list(cols) + [False]):
        if c and start is None: start = x
        if not c and start is not None:
            if x - start > 40: runs.append([start, x])
            start = None
    merged = []
    for rr in runs:
        if merged and rr[0] - merged[-1][1] < 25: merged[-1][1] = rr[1]
        else: merged.append(rr)
    return im, merged
meta = json.load(open('sprite_meta.json'))
OTHERS = ['maybe', 'kreed', 'slava', 'atl', 'korzh', 'face', 'chip']
for c in OTHERS: meta[c] = json.load(open(f'{c}_meta.json'))
for cid, fid in SRC.items():
    im, figs = figures(U + fid + '-image.png')
    if len(figs) != 3: print('!!', cid, figs)
    crops = []
    for x0, x1 in figs[:3]:
        c = im.crop((max(0, x0 - 6), 0, min(im.width, x1 + 6), im.height))
        c.save('moves_gen/tmp.png'); crops.append(clean('moves_gen/tmp.png'))
    # scale: by the light_0 frame width? use idle height vs overhead height (raised arm ~ +12%)
    idle = Image.open(f'game/assets/sprites/{cid}_idle.png'); bb = idle.getbbox(); IH = bb[3] - bb[1] - 2
    k = IH * 1.12 / crops[1].height * FIX.get(cid, 1.0)
    for pose, cr in zip(POSES, crops):
        sm = scale(cr, k); ax, ay = anchor(sm)
        sm.save(f'game/assets/sprites/{cid}_{pose}.png', optimize=True)
        meta[cid][pose] = {'src': f'assets/sprites/{cid}_{pose}.png', 'ax': round(ax), 'ay': round(ay)}
    print(cid, [c.size for c in crops], round(k, 3), IH)
for c in OTHERS:
    json.dump(meta[c], open(f'{c}_meta.json', 'w'), indent=1)
json.dump({k: v for k, v in meta.items() if k not in OTHERS}, open('sprite_meta.json', 'w'), indent=1)
m = json.load(open('sprite_meta.json'))
for c in OTHERS:
    mm = json.load(open(f'{c}_meta.json')); mm.pop('_whip_root', None); m[c] = mm
open('game/sprites.js', 'w').write('// Generated by tools/build_*.py: frame image + anchor (feet centre) per pose.\nconst SPRITE_META = ' + json.dumps(m, separators=(',', ':')) + ';\n')
